[workspace]
members = ["meowbot-core", "meowbot-ai", "meowbot-db", "meowbot-platform", "meowbot-weather", "meowbot-proto"]
resolver = "2"

[workspace.lints.clippy]
nursery = { level = "warn", priority = -1 }
multiple_crate_versions = "allow"

[workspace.lints.rustdoc]
all = "deny"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
