[package]
name = "greeting"
version = "0.7.0-beta2"
edition = "2024"
description = "Greeting Bot is a Telegram bot, which sends a message to all users in database with AI-generated text."
license-file = "LICENSE"
repository = "https://github.com/OneProgGit/GreetingBot"

[workspace]
members = ["services/core", "services/ai", "services/db", "services/platforms", "services/weather"]

[lints]
workspace = true

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
multiple_crate_versions = "allow"

[workspace.lints.rustdoc]
all = "deny"
missing_docs = "deny"

[workspace.dependencies]
tonic = "0.14.2"
prost = "0.14.1"
prost-types = "0.14.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[build-dependencies]
tonic-prost-build = "0.14.2"
