[package]
name = "meowbot"
version = "0.7.0"
edition = "2024"

[workspace]
members = ["meowbot-core", "meowbot-ai", "meowbot-db", "meowbot-platforms", "meowbot-weather", "meowbot-proto"]

[workspace.lints.clippy]
nursery = { level = "deny", priority = -1 }
multiple_crate_versions = "allow"

[workspace.lints.rustdoc]
all = "deny"
missing_docs = "deny"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"