[package]
name = "meowbot-ai"
version = "0.7.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
meowbot-proto = { version = "0.7.0", path = "../meowbot-proto" }
ollama-rs = "0.3.2"
prost = "0.14.1"
prost-types = "0.14.1"
regex = "1.11.3"
string_format = "0.1.0"
tokio = { version = "1.47.1", features = ["rt-multi-thread"] }
tonic = "0.14.2"

[lints]
workspace = true
