[package]
name = "meowbot-platform"
version = "0.7.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
meowbot-proto = { version = "0.7.0", path = "../meowbot-proto" }
prost = "0.14.1"
prost-types = "0.14.1"
teloxide = { version = "0.17.0", features = ["macros"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread"] }
tonic = "0.14.2"

[lints]
workspace = true
